/vis/open OGL
/vis/viewer/set/viewpointVector 1 0.5 0.5
/vis/drawVolume
/vis/viewer/set/autoRefresh true

/vis/scene/add/trajectories smooth
/vis/scene/add/trajectories rich 5
/vis/scene/add/hits
/vis/scene/add/scale 0.05 mm
/vis/scene/add/axes
/tracking/storeTrajectory 1
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate

# Fix: Use DrawByParticleID instead of DrawByAttribute
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/setLineStyle solid
#/vis/modeling/trajectories/drawByParticleID-0/setLineWidth 2
